#
# Makefile for sensor chip drivers.
#

obj-$(CONFIG_UAV_SENSORS_MPU6050)	+= mpu6050.o
obj-$(CONFIG_UAV_SENSORS_FBM320)	+= fbm320.o
obj-$(CONFIG_UAV_SENSORS_KS103)		+= ks103.o
obj-$(CONFIG_UAV_SENSORS_QMC5883)	+= qmc5883.o
obj-$(CONFIG_UAV_SENSORS_HMC5883)	+= hmc5883.o
obj-$(CONFIG_UAV_SENSORS_GPS_POWER)	+= gps_power.o
obj-$(CONFIG_UAV_SENSORS_LIS3MDL)	+= lis3mdl.o
