ifneq ($(strip $(CONFIG_ARCH_SUN8IW8)),)

else
obj-$(CONFIG_CSI_VFE)           += actuator.o
obj-m           += ad5820_act.o
obj-m           += dw9714_act.o
obj-m           += ov8825_act.o
obj-m           += vm149c_act.o
obj-m           += dw9718_act.o
obj-m           += dw9800_act.o
endif
