#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_GSLX680NEW) += gslX680new.o
#gslX680new-objs := gslX680.o
#gslX680new-objs := gslX680.o gsl_point_id_20131111
gslX680new-objs := gslX680.o gsl_point_id_20141114
#gslX680new-objs := gslX680.o gsl_point_id_20151027
