obj-y += nand.o

nand-objs += nand_interface.o \
	nfd/nand_ota_burn.o \
	nfd/boot_head/boot0_op.o \
	nfd/nand_base.o \
	nfd/nand_blk.o \
	nfd/nand_dev.o \
	nfd/nand_class.o \
	nfd/nand_osal_for_linux.o \
	lib/src/nftl/nftl_list.o  \
 	lib/src/nftl/nftl_logic.o \
 	lib/src/nftl/nftl_gc.o \
 	lib/src/nftl/nftl_cache.o \
 	lib/src/nftl/nftl_sector_cache.o \
 	lib/src/nftl/nftl_common.o \
 	lib/src/nftl/nftl_build.o \
 	lib/src/nftl/nftl_start.o \
 	lib/src/nftl/nftl_interface.o \
 	lib/src/nftl_interface/nftl_init.o \
 	lib/src/nftl_interface/nftl_hw_interface.o \
 	lib/src/nftl_interface/nftl_uboot_interface.o \
 	lib/src/physic/nand_format.o \
 	lib/src/physic/nand_id.o \
 	lib/src/physic/nand_phy.o \
 	lib/src/physic/nand_physic_interface.o \
 	lib/src/physic/nand_scan.o \
 	lib/src/physic/nand_simple_r.o \
 	lib/src/physic/nand_simple_w.o \
 	lib/src/physic/nfc_reg.o \
 	lib/src/physic/nfc_r.o \
 	lib/src/physic/nfc_w.o \
 	lib/src/phy/build_nand_partition.o \
 	lib/src/phy/build_phy_partition.o \
 	lib/src/phy/hw_phy.o \
 	lib/src/phy/nand_info_init.o \
 	lib/src/phy/phy_input.o    	\
 	lib/src/phy_v2/nand_info_init_v2.o \
 	lib/src/phy_v2/build_phy_partition_v2.o
