obj-$(CONFIG_LCD_SUNXI) += lcd.o

lcd-objs := dev_lcd.o lcd_source_interface.o lcd_panel_cfg.o panels/panels.o
lcd-objs += panels/default_panel.o
lcd-objs += panels/tft720x1280.o
lcd-objs += panels/vvx10f004b00.o
lcd-objs += panels/lp907qx.o
lcd-objs += panels/starry768x1024.o
lcd-objs += panels/sl698ph_720p.o
lcd-objs += panels/B116XAN03.o
lcd-objs += panels/LHR050H41_MIPI_RGB.o
lcd-objs += panels/S070WV20_MIPI_RGB.o
              
lcd-$(CONFIG_TV_GM7121) += panels/gm7121_cvbs.o

